apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hhpxbx1io-go
  janus-idp.io/tekton: hhpxbx1io-go
  backstage.io/kubernetes-id: hhpxbx1io-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hhpxbx1io-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
