apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hhpxbx1io-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hhpxbx1io-go 
  name: hhpxbx1io-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hhpxbx1io-go 
